## 1- Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Path for connect to CSV files location
data_path = Path("/Users/tonydawra/Downloads/projectfocstry/datasets")

#Abbreviations for each file according to file names
country_list = ['CA','DE','FR','GB','IN','JP','KR','MX','RU','US']

# This list for combine each country's DataFrame
all_files = []

#Loop for reading every CSV file based on country code and add a "country" column
for country in country_list:
    # Reaching each file based on country name
    file_path = data_path / f"{country}videos.csv"

    # Read the CSV; ignore errors because of "RUvideos", "JPvideos","USvideos" files
    df_country = pd.read_csv(file_path, encoding='utf-8', encoding_errors="ignore")

    # Creating new column for country names in order to concatenate
    df_country["country"] = country

    # Store this temporary DataFrame in the list
    all_files.append(df_country)

# Concatenate all DataFrames by using country column
df = pd.concat(all_files, ignore_index=True)

In [2]:
df.shape

(375942, 17)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375942 entries, 0 to 375941
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   video_id                375942 non-null  object
 1   trending_date           375942 non-null  object
 2   title                   375942 non-null  object
 3   channel_title           375942 non-null  object
 4   category_id             375942 non-null  int64
 5   publish_time            375942 non-null  object
 6   tags                    375942 non-null  object
 7   views                   375942 non-null  int64
 8   likes                   375942 non-null  int64
 9   dislikes                375942 non-null  int64
 10  comment_count           375942 non-null  int64
 11  thumbnail_link          375942 non-null  object
 12  comments_disabled       375942 non-null  bool
 13  ratings_disabled        375942 non-null  bool
 14  video_error_or_removed  375942 non-null  bool
 15  description             356464 non-null  object
 16  country                 375942 non-null  object
dtypes: bool(3), int64(5), object(9)
memory usage: 41.2+ MB

In [4]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
category_id,375942.0,2.023230e+01,7.132413e+00,1.0,17.0,23.0,24.00,44.0
views,375942.0,1.326568e+06,7.098568e+06,117.0,46978.0,177370.5,647679.25,424538912.0
likes,375942.0,3.788431e+04,1.654131e+05,0.0,669.0,3446.0,17476.50,5613827.0
dislikes,375942.0,2.126107e+03,2.248437e+04,0.0,41.0,179.0,749.00,1944971.0
comment_count,375942.0,4.253775e+03,2.545876e+04,0.0,109.0,511.0,2011.00,1626501.0

In [5]:
df.nunique(dropna=False).sort_values(ascending=False)

views                     240399
title                     186272
thumbnail_link            185690
video_id                  184287
publish_time              169286
description               156166
tags                      142211
likes                      73693
channel_title              37824
comment_count              24477
dislikes                   16715
trending_date                205
category_id                   18
country                       10
comments_disabled              2
video_error_or_removed         2
ratings_disabled               2
dtype: int64

In [6]:
sample_uniques = pd.DataFrame({
    "n_unique": df.nunique(dropna=False),
    "sample_values": df.columns.map(
        lambda c: list(pd.Series(df[c].dropna().unique())[:20])
    )
}, index=df.columns)
sample_uniques

,n_unique,sample_values
video_id,184287,"[n1WpP7iowLc, 0dBIkQ4Mz1M, 5qpjK5DgCt4, d380me..."
trending_date,205,"[17.14.11, 17.15.11, 17.16.11, 17.17.11, 17.18..."
title,186272,"[Eminem - Walk On Water (Audio) ft. Beyoncé, P..."
channel_title,37824,"[EminemVEVO, iDubbbzTV, Rudy Mancuso, nigahiga..."
category_id,18,"[10, 23, 24, 25, 22, 26, 1, 28, 20, 17, 29, 15..."
publish_time,169286,"[2017-11-10T17:00:03.000Z, 2017-11-13T17:00:00..."
tags,142211,"[Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/I..."
views,240399,"[17158579, 1014651, 3191434, 2095828, 33523622..."
likes,73693,"[787425, 127794, 146035, 132239, 1634130, 1037..."
dislikes,16715,"[43420, 1688, 5339, 1989, 21082, 4613, 9850, 2..."
comment_count,24477,"[125882, 13030, 8181, 17518, 85067, 12143, 266..."
thumbnail_link,185690,[https://i.ytimg.com/vi/n1WpP7iowLc/default.jp...
comments_disabled,2,"[False, True]"
ratings_disabled,2,"[False, True]"
video_error_or_removed,2,"[False, True]"
description,156166,[Eminem's new track Walk on Water ft. Beyoncé ...
country,10,"[CA, DE, FR, GB, IN, JP, KR, MX, RU, US]"

In [7]:
df.isna().sum().sort_values(ascending=False)

(df.isna().mean()*100).round(2).sort_values(ascending=False)

df.columns[df.isna().any()].tolist()

rows_with_na = df[df.isna().any(axis=1)]
rows_with_na.shape
rows_with_na

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
115,_QHEPUKBn9g,17.14.11,‘Too Alabama for Alabama’: SNL brutally mocks ...,MAXI POWER,23,2017-11-12T05:01:18.000Z,[none],20163,44,34,8,https://i.ytimg.com/vi/_QHEPUKBn9g/default.jpg,False,False,False,NaN,CA
128,JdHovvb0KD4,17.14.11,Pres. Trump: Putin's Denials Of Interference I...,The View,25,2017-11-13T16:10:21.000Z,"donald trump|""vladimir putin""|""the view""|""hot ...",72253,1217,146,569,https://i.ytimg.com/vi/JdHovvb0KD4/default.jpg,False,False,False,NaN,CA
165,OA0vhAKUD0g,17.14.11,Outlander S03E09 i'm melting with you'',Ella bell,1,2017-11-12T22:33:48.000Z,[none],32941,149,2,5,https://i.ytimg.com/vi/OA0vhAKUD0g/default.jpg,False,False,False,NaN,CA
179,psDauoxUj9A,17.14.11,شاهد انبهار الاعلام المصري بتأهل المغرب لكأس ...,Info Press,17,2017-11-11T22:04:37.000Z,[none],624328,7100,398,971,https://i.ytimg.com/vi/psDauoxUj9A/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375118,1h7KV2sjUWY,18.10.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1021063,58806,376,3903,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375318,1h7KV2sjUWY,18.11.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1024052,58862,377,3904,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375531,1h7KV2sjUWY,18.12.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1029290,58980,377,3931,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375732,1h7KV2sjUWY,18.13.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1034480,59090,379,3927,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

In [8]:
cols_with_nulls = df.columns[df.isna().any()].tolist()
cols_with_nulls

['description']

In [9]:
null_counts = df[cols_with_nulls].isna().sum().sort_values(ascending=False)
pd.DataFrame({"null_count": null_counts})

             null_count
description       19478

## 2- Delete no tags

In [10]:
#none value types
bad_values = ['[none]', '', 'none', 'None', 'NaN']


#exclude the rows which contains bad_values and keep the rows except NAN values
df = df[~df['tags'].isin(bad_values) & df['tags'].notna()]
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375936,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18T16:39:29.000Z,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",US
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

## 3. For each channel, determine the total number of views

In [11]:
#copy the df to not effect to original one
df1=df.copy()

#filtering df which channel title equals to T-Series
a=df1[df1['channel_title'] == 'T-Series']

#sorting views starting the most biggest one
a.sort_values('views',ascending=False)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
170741,xWi8nDUjHGA,18.02.01,Yo Yo Honey Singh: DIL CHORI (Video) Simar Kau...,T-Series,10,2017-12-26T09:49:35.000Z,"latest hindi songs|""bollywood""|""songs""|""2017""|...",34631260,645921,45039,58459,https://i.ytimg.com/vi/xWi8nDUjHGA/default.jpg,False,False,False,Presenting Yo Yo Honey Singh’s latest offering...,IN
170482,xWi8nDUjHGA,18.01.01,Yo Yo Honey Singh: DIL CHORI (Video) Simar Kau...,T-Series,10,2017-12-26T09:49:35.000Z,"latest hindi songs|""bollywood""|""songs""|""2017""|...",32535618,626476,43712,57321,https://i.ytimg.com/vi/xWi8nDUjHGA/default.jpg,False,False,False,Presenting Yo Yo Honey Singh’s latest offering...,IN
170249,xWi8nDUjHGA,17.31.12,Yo Yo Honey Singh: DIL CHORI (Video) Simar Kau...,T-Series,10,2017-12-26T09:49:35.000Z,"latest hindi songs|""bollywood""|""songs""|""2017""|...",29994900,602463,41911,55011,https://i.ytimg.com/vi/xWi8nDUjHGA/default.jpg,False,False,False,Presenting Yo Yo Honey Singh’s latest offering...,IN
184673,q2gICJFG6uw,18.24.03,Baaghi 2: Ek Do Teen Song | Jacqueline Fernand...,T-Series,10,2018-03-19T05:30:44.000Z,"ek do teen|""ek do teen baaghi 2""|""baaghi 2 son...",29503026,320346,80059,31872,https://i.ytimg.com/vi/q2gICJFG6uw/default.jpg,False,False,False,Ek Do Teen Chaar Song | Baaghi 2 New Song | Ja...,IN
191025,aNwWdF8qq-M,18.03.05,Official Video: Raat Kamaal Hai | Guru Randhaw...,T-Series,10,2018-04-26T05:33:22.000Z,"latest hindi songs|""bollywood songs""|""songs""|""...",27893636,397141,43165,27596,https://i.ytimg.com/vi/aNwWdF8qq-M/default.jpg,False,False,False,Gulshan Kumar and T-Series present Bhushan Kum...,IN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166000,vIA73i3Juwk,17.08.12,Bulbul: Short Film | Divya Khosla Kumar | Shiv...,T-Series,10,2017-12-07T06:32:47.000Z,"Divya Khosla Kumar|""Bulbul""|""Bulbul short film...",119511,8445,534,588,https://i.ytimg.com/vi/vIA73i3Juwk/default.jpg,False,False,False,"Presenting the Short Film Bulbul, Starring Div...",IN
167114,9vnhToVxgUU,17.14.12,Song Teaser: SunDowner | AVI J | Releasing On ...,T-Series,10,2017-12-13T10:57:21.000Z,"avi j songs|""latest punjabi song""|""deep jandu""...",113408,1316,211,158,https://i.ytimg.com/vi/9vnhToVxgUU/default.jpg,False,False,False,We present to you the teaser of the upcoming s...,IN
179280,5sVGug6dxt4,18.20.02,Official Teaser: The Remix | Amazon Prime Vid...,T-Series,10,2018-02-19T11:49:34.000Z,"Music show|""Music reality show""|""Music show bo...",92830,1257,230,172,https://i.ytimg.com/vi/5sVGug6dxt4/default.jpg,False,False,False,Presenting the official teaser of the upcoming...,IN
166521,yvDUw2rdaeg,17.11.12,T-Series Mixtape Punjabi: 3 Peg/Label Black So...,T-Series,10,2017-12-10T12:30:02.000Z,"sharry mann|""sharry maan punjabi""|""sharry maan...",78093,1262,174,286,https://i.ytimg.com/vi/yvDUw2rdaeg/default.jpg,False,False,False,Gulshan Kumar Presents Bhushan Kumar's T-Serie...,IN
166417,7dgjSAaLC3U,17.10.12,T-Series Mixtape Punjabi: 3 Peg/Label Black So...,T-Series,10,2017-12-09T13:45:08.000Z,"sharry mann|""sharry maan punjabi""|""sharry maan...",57483,1084,95,145,https://i.ytimg.com/vi/7dgjSAaLC3U/default.jpg,False,False,False,Gulshan Kumar Presents Bhushan Kumar's T-Serie...,IN

In [12]:
#convert to trending_date types to datetime type
df["trending_date"] = pd.to_datetime(df["trending_date"],format='%y.%d.%m')

#sorting values according to video_id and trending_date
#earliest trending date comes first
df_sorted = df.sort_values(["video_id", "trending_date"])

#find the most recent trending date for each video (a video can trend multiple times,but we want its latest view count)
df_last = df_sorted.drop_duplicates(subset="video_id", keep="last")
channel_views = (
    df_last.groupby("channel_title")["views"]
    .sum()
    .sort_values(ascending=False))
channel_views_df =channel_views.to_frame("total_views").reset_index()
channel_views_df

               channel_title  total_views
0                   T-Series    549514687
1                      Ozuna    496503490
2                 NickyJamTV    467892045
3                  DrakeVEVO    364312023
4                  Bad Bunny    357112379
...                      ...          ...
30559  Сергей Автоинструктор          396
30560       Videostendencias          302
30561          No Comment TV          284
30562             Sport Life          163
30563      Alexander Redking          153

[30564 rows x 2 columns]

## 4-Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [13]:
# Keep the rows that meet one of these conditions:
#  comments_disabled == True AND ratings_disabled == True
#  video_error_or_removed == True
excluded = df[((df["comments_disabled"] == True) & (df["ratings_disabled"] == True)) | (df["video_error_or_removed"] == True)]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
173,H8IWLEtFt9A,2017-11-14,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,2017-11-19,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,2017-11-20,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,2017-11-20,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,2017-11-21,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,2018-05-07,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,2018-05-08,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,2018-05-09,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,2018-05-10,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,2018-05-14,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

In [14]:
excluded.shape

(2131, 17)

In [15]:
#removing excluded rows, and make sure about the row numbers equality

df = df[~(((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True))]
df.shape

(336113, 17)

## 5- Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [16]:
#if one of the value is nan, delete that row (if there are any 0, it create error because system can't divide with 0)
df_filtered = df[['likes', 'dislikes']].dropna()

#exclude 0 values for dislike for right dividing
df_filtered = df_filtered[df_filtered['dislikes'] > 0]

#find the ratio
df_filtered['like_ratio'] = df_filtered['likes'] / df_filtered['dislikes']

#create new column in df , still keeping nan value rows ??
df.loc[df_filtered.index, 'like_ratio'] = df_filtered['like_ratio']
df

/var/folders/mp/yz1h5zm55vggj3tcjjgkpv_80000gn/T/ipykernel_26059/3635486891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df_filtered.index, 'like_ratio'] = df_filtered['like_ratio']

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375936,1PhPYr_9zRY,2018-06-14,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18T16:39:29.000Z,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",US,159.399803
375937,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347
375939,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519
375940,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368
375941,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616

In [17]:
#showing the like_ratio column

df[df["dislikes"] > 0][["likes", "dislikes", "like_ratio"]] \
    .sort_values("like_ratio", ascending=False)

        likes  dislikes    like_ratio
331431  11688         1  11688.000000
296366  14203         4   3550.750000
221150  14202         4   3550.500000
113540   3177         1   3177.000000
4508    25599         9   2844.333333
...       ...       ...           ...
300298      0         6      0.000000
41315       0         1      0.000000
91201       0         1      0.000000
309372      0         1      0.000000
301125      0        24      0.000000

[330313 rows x 3 columns]

## 6- Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [18]:
df = df.copy()
df["publish_time"] = pd.to_datetime(df["publish_time"], errors="coerce")

# start of the 10-minute interval and convert to closest 10-minute
interval_start = df["publish_time"].dt.floor("10min")

# end = start + 10 minutes
interval_end = interval_start + pd.Timedelta(minutes=10)

# string label with just hour and minute information
df["publish_interval_10m_time"] = (
    interval_start.dt.strftime("%H:%M")
    + " to "
    + interval_end.dt.strftime("%H:%M")
)

# checking df
df[["publish_time", "publish_interval_10m_time"]].head()

               publish_time publish_interval_10m_time
0 2017-11-10 17:00:03+00:00            17:00 to 17:10
1 2017-11-13 17:00:00+00:00            17:00 to 17:10
2 2017-11-12 19:05:24+00:00            19:00 to 19:10
3 2017-11-12 18:01:41+00:00            18:00 to 18:10
4 2017-11-09 11:04:14+00:00            11:00 to 11:10

## 7- For each interval, determine the number of videos, average number of likes and of dislikes.

In [19]:
# Grouping the videos by the 10-minute interval
interval_stats = (
    df.groupby("publish_interval_10m_time")
      .agg(
          videos_per_interval = ("video_id", "size"),   # how many videos
          avg_likes          = ("likes", "mean"),       # avg likes
          avg_dislikes       = ("dislikes", "mean")     # avg dislikes
      )
      .reset_index()
      .sort_values("publish_interval_10m_time")         # optional just to order nicely
)

interval_stats

    publish_interval_10m_time  videos_per_interval     avg_likes  avg_dislikes
0              00:00 to 00:10                 2570  68240.263035   4272.435019
1              00:10 to 00:20                 1336  25436.401946   1620.327096
2              00:20 to 00:30                 1027  25392.919182   1268.650438
3              00:30 to 00:40                 1384  42547.976156   1064.950145
4              00:40 to 00:50                 1088  48723.898897   2178.424632
..                        ...                  ...           ...           ...
139            23:10 to 23:20                 1373  25551.304443   1243.988347
140            23:20 to 23:30                 1228  35537.941368   1270.521987
141            23:30 to 23:40                 1455  20558.467354    981.274227
142            23:40 to 23:50                 1248  53549.919071  10959.288462
143            23:50 to 00:00                 1041  12774.178674    600.080692

[144 rows x 4 columns]

## 8- For each tag, determine the number of videos
Notice that tags contains a string with several tags.

In [20]:
# Work on a copy to keep original data
df_tags = df.copy()

# Explode the "tags" string into one row per tag:
# Drop NaN value rows for tags
# Split the "tags" string on "|" into a list
# explode() creates one row per element of that list

#exploding each tag in the cell and adding extra rows for each different tag of  each video_id
df_tags_exploded = (
    df_tags
    .dropna(subset=["tags"])
    .assign(tag_list=lambda x: x["tags"].str.split("|"))
    .explode("tag_list")
)

# Clean the exploded tag: remove extra spaces and surrounding quotes
df_tags_exploded["tag"] = (
    df_tags_exploded["tag_list"]
    .str.replace('"','')
    .str.strip("|")
)

# We no longer need the intermediate list column
df_tags_exploded = df_tags_exploded.drop(columns=["tag_list"])

# Inspect how tags look now
df_tags_exploded[["video_id", "tags", "tag", "country"]]

,video_id,tags,tag,country
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Eminem,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Walk,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",On,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Water,CA
0,n1WpP7iowLc,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",Aftermath/Shady/Interscope,CA
...,...,...,...,...
375940,oV0zkMe1K8s,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",ending explained,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",call of duty,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",cod,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",activision,US
375941,ooyjaVdt-jA,"call of duty|""cod""|""activision""|""Black Ops 4""",Black Ops 4,US

## 9- Find the tags with the largest number of videos

In [21]:
# Count how many *distinct* videos contain each tag
videos_per_tag = (
    df_tags_exploded.groupby("tag")["video_id"]
    .nunique()                     # number of distinct videos per tag
    .reset_index(name="n_videos")
)

In [22]:
# Descending number of videos and display top 10
top_tags = videos_per_tag.sort_values("n_videos", ascending=False)
top_tags.head(10)

               tag  n_videos
12818         2018      5750
355882       funny      4148
296168      comedy      3105
466731        news      3051
12466         2017      2655
586271       video      2076
535430        show      2046
576605          tv      1731
560124  television      1720
694945     новости      1549

## 10- For each (tag, country) pair, compute average ratio likes/dislikes

In [23]:
# Removes the videos which like ratio values is nan (using df_tags_exploded )
valid_ratio_tags = df_tags_exploded.dropna(subset=['like_ratio'])


# Group by tag and country, then calculate the MEAN of the like_ratio

avg_like_ratio = valid_ratio_tags.groupby(['tag', 'country'])['like_ratio'].mean().reset_index()


# Assign new name to like raito column and sort
avg_like_ratio = avg_like_ratio.rename(columns={'like_ratio': 'average_like_ratio'})
avg_like_ratio = avg_like_ratio.sort_values('average_like_ratio', ascending=False)
# Display result
avg_like_ratio

                          tag country  average_like_ratio
29880                    AT&T      RU             11688.0
29882           AT&T AUDIENCE      RU             11688.0
30062        AUDIENCE Network      RU             11688.0
30011                     ATT      RU             11688.0
29884          AT&T Originals      RU             11688.0
...                       ...     ...                 ...
965931                  الحدث      RU                 0.0
982113             هم الأخبار      RU                 0.0
648610           pasportslive      RU                 0.0
769869  top advertising rates      RU                 0.0
527658            iphone case      DE                 0.0

[1082980 rows x 3 columns]

## 11- For each (trending_date, country) pair, the video with the largest number of views

In [24]:
# finding row number of maximum value of views for each (trending_date, country) pair
idx = df.groupby(["trending_date", "country"])["views"].idxmax()

# Retrieving other columns of idx from the original data
top_trending_videos = df.loc[idx, ["trending_date", "country", "video_id", "title", "views"]]

# cleaning the indexes
top_trending_videos = top_trending_videos.reset_index()

# Sorting df based on views
top_trending_videos = top_trending_videos.sort_values("views", ascending=False)

top_trending_videos

,index,trending_date,country,video_id,title,views
1340,150857,2018-04-07,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,424538912
1330,150657,2018-04-06,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,413586699
1320,150453,2018-04-05,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,402650804
1310,150256,2018-04-04,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,392036878
1300,150060,2018-04-03,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,382401497
...,...,...,...,...,...,...
322,301252,2017-12-19,RU,Cd0EbzegNH0,Выборы объявлены. Наши ближайшие планы,1086379
133,297082,2017-11-28,RU,vanibZ9VYqA,РВАТЬ НА БИТАХ - ЕЖЕМЕСЯЧНЫЕ Х БЕССЛАВНЫЕ УБЛЮ...,1078832
1312,208277,2018-04-04,JP,ut6UYwbt6Xk,Honest Trailers - Jumanji: Welcome To The Jungle,1063506
1112,204901,2018-03-15,JP,_dn_8RR3SyY,Hungry To Leave Power Games: Rex Tillerson,1053654
1452,210679,2018-04-24,JP,v9GODjGXju0,Free Speech Under Fire In Controversial Nazi P...,933552

## 12- Divide trending_date into three columns: year, month, day

In [25]:
#convert to trending_datetime to year.day.month format
df["trending_datetime"] = pd.to_datetime(
    df["trending_date"],
    format="%y.%d.%m",
    errors="coerce"
)

# Extract year, month and day into different columns
df["trend_year"] = df["trending_datetime"].dt.year
df["trend_month"] = df["trending_datetime"].dt.month
df["trend_day"] = df["trending_datetime"].dt.day


df[["video_id", "trending_date", "trend_year", "trend_month", "trend_day"]]

           video_id trending_date  trend_year  trend_month  trend_day
0       n1WpP7iowLc    2017-11-14        2017           11         14
1       0dBIkQ4Mz1M    2017-11-14        2017           11         14
2       5qpjK5DgCt4    2017-11-14        2017           11         14
3       d380meD0W0M    2017-11-14        2017           11         14
4       2Vv-BfVoq4g    2017-11-14        2017           11         14
...             ...           ...         ...          ...        ...
375936  1PhPYr_9zRY    2018-06-14        2018            6         14
375937  BZt0qjTWNhw    2018-06-14        2018            6         14
375939  D6Oy4LfoqsU    2018-06-14        2018            6         14
375940  oV0zkMe1K8s    2018-06-14        2018            6         14
375941  ooyjaVdt-jA    2018-06-14        2018            6         14

[336113 rows x 5 columns]

## 13- For each (month, country) pair, the video with the largest number of views

In [26]:
# finding row number of maximum value of views for each (trend_month, country) pair
idx = df.groupby(["trend_month", "country"])["views"].idxmax()

# Retrieving other columns of idx row from the original data
top_trending_videos_month = df.loc[
    idx, ["trend_month", "country", "video_id", "title", "views"]
]

# cleaning the indexes
top_trending_videos_month = top_trending_videos_month.reset_index()

# Sorting the df to see the largest number of views
top_trending_videos_month = top_trending_videos_month.sort_values(
    "views", ascending=False
)

top_trending_videos_month

,index,trend_month,country,video_id,title,views
32,150857,4,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,424538912
22,149497,3,GB,_I_D_8Z4sJE,Nicky Jam x J. Balvin - X (EQUIS) | Video Ofic...,349987176
42,156905,5,GB,9jI-z9QN6g8,"Te Bote Remix - Casper, Nio García, Darell, Ni...",337621571
12,143402,2,GB,wfWkmURBNv8,Ozuna x Romeo Santos - El Farsante Remix,280125114
52,160846,6,GB,VYOjWnS4cMY,Childish Gambino - This Is America (Official V...,259721696
...,...,...,...,...,...,...
66,296828,11,RU,kTlv5_Bs8aw,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,20565795
57,332572,6,RU,aJOTlE1K90k,Maroon 5 - Girls Like You ft. Cardi B,17303018
17,313343,2,RU,xpVfcZ0ZcFM,Drake - God’s Plan,17059675
54,218859,6,JP,TIE92mUvSsw,Dhadak | Official Trailer | Janhvi & Ishaan | ...,15969920
14,198738,2,JP,pVxOVlm_lE8,Marvel Studios’ Avengers: Infinity War - Big G...,12908071

## 14- Read all json files with the video categories

In [27]:
import json

# Re-use the same data_path and country_list as first question

all_categories = []

for country in country_list:
    # finding each json file
    jf = data_path / f"{country}_category_id.json"

    # Read json.file content as string type
    raw_text = jf.read_text(encoding="utf-8")

    # transform the string to a Python object
    data = json.loads(raw_text)


    #items parts of the youtube API FORMAT
    #get each item, if they dont have return list
    items = data.get("items", [])

    # Flatten nested JSON into a DataFrame
    cat_df = pd.json_normalize(items)

    # Keep only ID, title, and assignable flag, and rename columns
    cat_df = cat_df[["id", "snippet.title", "snippet.assignable"]].rename(
        columns={
            "id": "category_id",
            "snippet.title": "category_name",
            "snippet.assignable": "assignable"
        }
    )

    # Make sure category_id is a string and add the country column
    cat_df["category_id"] = cat_df["category_id"].astype(str)
    cat_df["country"] = country

    # Store this intermediate DataFrame
    all_categories.append(cat_df)

# One big DataFrame with all categories and all countries
categories_df = pd.concat(all_categories, ignore_index=True)

categories_df.head(30)

   category_id         category_name  assignable country
0            1      Film & Animation        True      CA
1            2      Autos & Vehicles        True      CA
2           10                 Music        True      CA
3           15        Pets & Animals        True      CA
4           17                Sports        True      CA
5           18          Short Movies       False      CA
6           19       Travel & Events        True      CA
7           20                Gaming        True      CA
8           21         Videoblogging       False      CA
9           22        People & Blogs        True      CA
10          23                Comedy        True      CA
11          24         Entertainment        True      CA
12          25       News & Politics        True      CA
13          26         Howto & Style        True      CA
14          27             Education        True      CA
15          28  Science & Technology        True      CA
16          30                Movies       False      CA
17          31       Anime/Animation       False      CA
18          32      Action/Adventure       False      CA
19          33              Classics       False      CA
20          34                Comedy       False      CA
21          35           Documentary       False      CA
22          36                 Drama       False      CA
23          37                Family       False      CA
24          38               Foreign       False      CA
25          39                Horror       False      CA
26          40        Sci-Fi/Fantasy       False      CA
27          41              Thriller       False      CA
28          42                Shorts       False      CA
29          43                 Shows       False      CA

## 15- For each country, determine how many videos have a category that is not assignable.

In [28]:
# Filter categories that are NOT assignable
categories_nassignable = categories_df[categories_df["assignable"] == False]

# make sure category_id has same datatype in different df for merging
categories_nassignable["category_id"] = categories_nassignable["category_id"].astype(str)
df["category_id"] = df["category_id"].astype(str)


# merging 2 different df on category id and country (both df have same column name)
df_merge = categories_nassignable.merge(
    df,
    on=["category_id", "country"],
    how="inner"
)

# Group by country and non-assignable category_id and count how many videos
assignable_video = df_merge.groupby(["country", "category_id"])["video_id"].count()

assignable_video

/var/folders/mp/yz1h5zm55vggj3tcjjgkpv_80000gn/T/ipykernel_26059/497069419.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  categories_nassignable["category_id"] = categories_nassignable["category_id"].astype(str)

country  category_id
CA       30               6
         43             123
DE       30               2
         43             106
FR       30              11
         43              99
GB       43              20
IN       30              16
         43             205
KR       43             165
MX       43               3
RU       30               1
         43             194
US       43              57
Name: video_id, dtype: int64